version: '3.8'

services:
  face-recognition-portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face-recognition-portal
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Optional: Add volumes for persistent data if needed in the future
# volumes:
#   app-data: 